// <auto-generated />
namespace ControlePedidos.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nova_Tabela_Item_Orcamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nova_Tabela_Item_Orcamento));
        
        string IMigrationMetadata.Id
        {
            get { return "201804060137331_nova_Tabela_Item_Orcamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
