// <auto-generated />
namespace ControlePedidos.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class colun_clienteId_NovoPedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(colun_clienteId_NovoPedido));
        
        string IMigrationMetadata.Id
        {
            get { return "201804131238446_colun_clienteId_NovoPedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
