// <auto-generated />
namespace ControlePedidos.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class correcao_relacionamento_clienteendereco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correcao_relacionamento_clienteendereco));
        
        string IMigrationMetadata.Id
        {
            get { return "201804211138428_correcao_relacionamento_cliente-endereco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
