// <auto-generated />
namespace ControlePedidos.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ad_referencia_cliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ad_referencia_cliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201805020018437_ad_referencia_cliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
