// <auto-generated />
namespace ControlePedidos.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remodelagem_da_base_tabela_item_pedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remodelagem_da_base_tabela_item_pedido));
        
        string IMigrationMetadata.Id
        {
            get { return "201802060053429_remodelagem_da_base_tabela_item_pedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
