// <auto-generated />
namespace ControlePedidos.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tab_ItemPedido_E_Pedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tab_ItemPedido_E_Pedido));
        
        string IMigrationMetadata.Id
        {
            get { return "201804130004553_tab_ItemPedido_E_Pedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
