// <auto-generated />
namespace ControlePedidos.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class atualiza_tb_itens_Pedido1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualiza_tb_itens_Pedido1));
        
        string IMigrationMetadata.Id
        {
            get { return "201804130225550_atualiza_tb_itens_Pedido1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
